### ISSUE TITLE
请问有什么方法能提高爬虫速度吗

### ISSUE THREAD

**Issue by LBingRun** [kong36088/ZhihuSpider#4]
当爬虫速度稍微快一点就会被知乎察觉，并且封号，爬虫速度目前大概一小时能爬1300条左右，再快的话就会被封

**Comment by kong36088** [comment]
没有别的什么更好的办法了，知乎的反爬有点严重，只能减慢速度。可以试着换ip去爬，爬虫的master分支是无登陆版本的可以试试。
